#!/bin/bash
FILE=consola
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE ./cfg/consola.cfg ./cfg/DEADLOCK_3.pse
fi