#!/bin/bash
FILE=memoria
make ./bin/$FILE.out
if test -f "./bin/$FILE.out"; then
    valgrind --leak-check=full --show-leak-kinds=all --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./bin/$FILE.out ./cfg/$FILE.cfg 
fi