#!/bin/bash
FILE=kernel
make ./bin/$FILE.out
if test -f "./bin/$FILE.out"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./bin/$FILE.out ./cfg/$FILE.cfg 
fi